test:
  workers:
    type: local
    number: 10
  rounds:
    - label: initLedger 
      txNumber: 1
      rateControl:
          type: fixed-rate
          opts:
            tps: 1
      workload:
        module: ./workloads/electronic-health-record/initLedger.js

    - label: common
      txNumber: 5000
      rateControl:
          type: fixed-rate
          opts:
            tps: 100
      workload:
        module: ./workloads/electronic-health-record/common2.js

    - label: common
      txNumber: 5000
      rateControl:
          type: fixed-rate
          opts:
            tps: 100
      workload:
        module: ./workloads/electronic-health-record/common1.js

