test:
  workers:
    type: local
    number: 10
  rounds:
    - label: initLedger
      txNumber: 1
      rateControl:
          type: fixed-rate
          opts:
            tps: 1
      workload:
        module: /caliper-workload/initLedger.js

    - label: common
      txNumber: 1500
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: /caliper-workload/common_oneread1.js

    - label: common
      txNumber: 1500
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: /caliper-workload/common_oneread2.js

    - label: common
      txNumber: 1500
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: /caliper-workload/common_oneread3.js

    - label: common
      txNumber: 1500
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: /caliper-workload/common_oneread4.js

    - label: common
      txNumber: 2000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: /caliper-workload/common_oneread.js


