test:
  workers:
    type: local
    number: 10
  rounds:
    - label: initLedger
      txNumber: 1
      rateControl:
          type: fixed-rate
          opts:
            tps: 1
      workload:
        module: ./workloads/supplychain/initLedger.js

    - label: common
      txNumber: 2000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: ./workloads/supplychain/common1.js

    - label: common
      txNumber: 2000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: ./workloads/supplychain/common2.js

    - label: common
      txNumber: 2000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: ./workloads/supplychain/common3.js

    - label: common
      txNumber: 2000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: ./workloads/supplychain/common4.js

