test:
  workers:
    type: local
    number: 10

  rounds:
    - label: initLedger
      txNumber: 1
      rateControl:
          type: fixed-rate
          opts:
            tps: 1
      workload:
        module: ./workloads/drm_splitdw/initLedger.js

    - label: common
      txNumber: 8500
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: ./workloads/drm_splitdw/common1.js

#    - label: common
#      txDuration: 30
#      rateControl:
#          type: zero-rate
#          opts:
#            tps: 
#      workload:
#        module: ./workloads/drm_splitdw/common.js
        #
        #    - label: common
        #      txNumber: 10
        #      rateControl:
        #          type: fixed-rate
        #          opts:
        #            tps: 10
        #      workload:
        #        module: ./workloads/drm_splitdw/commontest1.js

    - label: common
      txNumber: 1500
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: ./workloads/drm_splitdw/common2.js

