test:
  workers:
    type: local
    number: 10
    #number: 17

  rounds:
    - label: initLedger
      txNumber: 10000
      rateControl:
          type: fixed-rate
          opts:
            tps: 100
      workload:
        module: /caliper-workload/initLedger.js

    - label: common
      txNumber: 10000
      #txNumber: 17000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: /caliper-workload/common.js

