test:
  workers:
    type: local
    number: 10

  rounds:
    - label: initLedger
      txNumber: 10000
      rateControl:
          type: fixed-rate
          opts:
            tps: 100
      workload:
        module: /caliper-workload/initLedger.js

    - label: common
      txNumber: 5000
      rateControl:
          type: fixed-rate
          opts:
            tps: 500
      workload:
        module: /caliper-workload/common.js

    - label: common
      txNumber: 5000
      rateControl:
          type: fixed-rate
          opts:
            tps: 500
      workload:
        module: /caliper-workload/common.js

