test:
  workers:
    number: 16
  rounds:
    - label: Create a car .
      txDuration: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 1400
          # transactionLoad: 2000
      workload:
        module: ./workloads/fabcar/createCar.js
